name: Rust Build

on:
  push:
    branches: [ "master" ]

variables:
  PROJECT_NAME: term_bounce

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, macos-14]
    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: cargo build --release
    - name: Archive release
      uses: actions/upload-artifact@v2
      with:
        name: "{{ variables.PROJECT_NAME }}-{{ matrix.os }}"
        path: target/release/{{ variables.PROJECT_NAME }}